# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Egate < Formula
  desc ""
  homepage "https://github.com/aka-somix/eventbridge-gate"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aka-somix/eventbridge-gate/releases/download/v0.1.0/eventbridge-gate_ 0.1.0_Darwin_x86_64.tar.gz"
      sha256 "dec052be22960c61f5e7ade2b76a7cb8224f54baebcec688e82335b1d44687f4"

      def install
        bin.install "egate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aka-somix/eventbridge-gate/releases/download/v0.1.0/eventbridge-gate_ 0.1.0_Darwin_arm64.tar.gz"
      sha256 "102f6ec6adce4e0f1ea6c99dd20a745989b07ca95b74b38f2c14841b26b6be69"

      def install
        bin.install "egate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aka-somix/eventbridge-gate/releases/download/v0.1.0/eventbridge-gate_ 0.1.0_Linux_x86_64.tar.gz"
        sha256 "6ce158298260d1cbfd6deb9ca52bf2d955314753b79b61c71d13bce47adeb6de"

        def install
          bin.install "egate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aka-somix/eventbridge-gate/releases/download/v0.1.0/eventbridge-gate_ 0.1.0_Linux_arm64.tar.gz"
        sha256 "7665decccaa9fe32ca411c219c450f3c52131dc3e417aa93a0e3315824058b58"

        def install
          bin.install "egate"
        end
      end
    end
  end
end
